# Generated by Django 4.2.18 on 2025-02-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_post_alter_profile_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="profile_image/blank-profile-picture.png",
                upload_to="profile_image",
            ),
        ),
    ]
