# Generated by Django 4.2.18 on 2025-02-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_likepost"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowersCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(
                default="profile_image\\blank-profile-picture.png",
                upload_to="profile_image",
            ),
        ),
    ]
